In [1]:
a=2
print(a)
type(a)

2


int

In [2]:
A="hello"
print(type(A),A)
b=2
print(type(b),b)
_9=2j+3
print(type(_9),_9)
_=2.5
print(type(_),_)

<class 'str'> hello
<class 'int'> 2
<class 'complex'> (3+2j)
<class 'float'> 2.5


In [3]:
x=str(input())
x

10


'10'

In [4]:
x=2.5
complex(x)

(2.5+0j)

In [5]:
a=2
print(float(a))
print(str(a))
print(complex(a))

2.0
2
(2+0j)


In [7]:
a=2j+3
print(float(a))
print(str(a))
print(int(a))

(3+2j)


TypeError: can't convert complex to int

In [8]:
a="hello"
b="world"
print(type(a+b),a)

<class 'str'> hello


In [9]:
a="hello world welcome to python class's to train tech's"
print(a)
len(a)
a.upper()
a.lower()
a.capitalize()

hello world welcome to python class's to train tech's


"Hello world welcome to python class's to train tech's"

In [10]:
a="3j+5"
b="3j+5"
print(len(a))
print(a.upper())
print(a.lower())


4
3J+5
3j+5


In [12]:
a="hello"
b="world"
c=a+b
print(len(c))
print(c.upper())
print(c.lower())


10
HELLOWORLD
helloworld


In [14]:
a="python"
a[1]
a[-2]

'o'

In [15]:
a=("hello python")
print(a.capitalize())
print(a.casefold())
print(a.center(50,"-"))

Hello python
hello python
-------------------hello python-------------------


In [16]:
print(len(a))
a.endswith('n')
a.endswith('n',1)

12


True

In [17]:
a="hello how are you"
index_position=a.find("how")
print(index_position)

6


In [18]:
import math
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [19]:
import math
print(math.sin(10))
print(math.cos(40))
print(math.tan(55))

-0.5440211108893698
-0.6669380616522619
-45.18308791052113


In [20]:
import math
x=2
print(math.radius(x),"rad")
print(math.exp(x),"exp")

AttributeError: module 'math' has no attribute 'radius'

In [21]:
c="5"
print(type(c))
print(int(c),float(c),complex(c))

<class 'str'>
5 5.0 (5+0j)


In [22]:
x="hello"
"h" in x

True

In [23]:
a=1001
b=1100
a and b

1100

In [24]:
a=0
b=1
a<<b

0

In [25]:
a=1
b=0
a>>b

1

In [26]:
a=[1,2,3,2j+4,"hello"]
print(a)

[1, 2, 3, (4+2j), 'hello']


In [27]:
a=list([1,2,3, 3j+5,"hi"])
print(a)

[1, 2, 3, (5+3j), 'hi']


In [28]:
a=tuple([1,2,5,2j+6])
print(a)

(1, 2, 5, (6+2j))


In [29]:
a=[1,2,3,4,5]
a[2]

3

In [30]:
a=[1,3,4,6,7]
a[0:3]

[1, 3, 4]

In [31]:
a="hello"
a[2]

'l'

In [33]:
a=[1,2,3,[1,2,3]]
a[2]

3

In [34]:
a=[[8,7,9],['i','x','y'],[3,4,6]]
print(a)

[[8, 7, 9], ['i', 'x', 'y'], [3, 4, 6]]


In [36]:
x=[1,2,3,4,7,8,5,9]
y=x
y[1:3]=[5:6]
print(x)

SyntaxError: invalid syntax (<ipython-input-36-6b4c01015943>, line 3)

In [1]:
x=list(['a','b','c'])
print(x)

['a', 'b', 'c']


In [2]:
a=[1,2,3,4]
l=list([a,'b','c','d'])
print(l)

[[1, 2, 3, 4], 'b', 'c', 'd']


In [3]:
n=["happy",[2,0,4,5]]
print(n[0][1],n[1][2],n[1][-1])

a 4 5


In [5]:
n=['p','q','r','s']
b=['1','2']
c=['1','2','3']
print(n.append('z'))
print(n.extend(b))
print(n.remove('p'))
print(n.insert(1,2))

None
None
None
None


In [6]:
n=['p','r','s','t']
n.insert(1,'hello')
n.pop(0)

'p'

In [7]:
a=[1,2,3]
a[0]=4
a

[4, 2, 3]

In [10]:
a=[1,2,3,4,5]
a[0:2]=8,9
a

[8, 9, 3, 4, 5]

In [11]:
a=["hello"]
a.insert(5,'h')
print(a)

['hello', 'h']


In [13]:
i=[a,b,c]
i.index(a)

0

In [15]:
a=[1,2,3,4,5]
print(min(a))
print(max(a))

1
5


In [18]:
a=[1,2,3,4]
b=[5]
sum=a+b
print(sum)

[1, 2, 3, 4, 5]


In [1]:
a=[2,3,5,4,6,7]
sum=sum(a)
print(sum)

27


In [2]:
my_tuple=("hello",1,2,3)
print(my_tuple)

('hello', 1, 2, 3)


In [3]:
my_tuple=([1,2,3],[1,6,7])
print(my_tuple)

([1, 2, 3], [1, 6, 7])


In [6]:
a=("pinky")
print(('repeat')*3)

repeatrepeatrepeat


In [7]:
x=[1,2,3,4,6]
x.sort()
print(x)

[1, 2, 3, 4, 6]


In [8]:
a=('p','a','r','s')
print('a' in a)
print('p' not in a)

True
False


In [9]:
p={1,2,3,4,5}
print(p)

{1, 2, 3, 4, 5}


In [12]:
Days=set(["mon","tue","wedn","thur","fri"])
months={"jan","feb","march"}
Dates={2,4,12}
Dates.add(11)
print(Days)
print(Dates)

{'mon', 'wedn', 'tue', 'fri', 'thur'}
{2, 11, 4, 12}


In [14]:
DaysA=set(["mon","tues","wed"])
DaysB=set(["thru","fri"])
AllDays=DaysA & DaysB
print(AllDays)

set()


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[4,3,7]])
print(np.shape(a))
print(np.size(a))

(3, 3)
9


TypeError: reshape() missing 1 required positional argument: 'newshape'

In [13]:
import numpy as np
a=np.arange(90)
print(a)
a=a.reshape(9,10)
print(a)
a=a.reshape(3,5,6)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]

 [[60 61 62 63 64 65]
  [66 67 68 69 70 71]
  [72 73 74 75 76 77]
  [78 79 80 81 82 83]
  [84 85 86 87 88 89]]]


In [19]:
import numpy as np
a=np.arange(100)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
